name: Build and Release EXE

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller python-dotenv

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --name health_bot_${{ github.ref_name }} health_bot.py

    - name: Upload EXE to Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/health_bot_${{ github.ref_name }}.exe
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
